version: '3'
services:
    api:
        image: node:12.18.4
        ports:
            - 3000:3000
        environment:
            - PGUSER=alicekres
            - PGHOST=db
            - PGPASSWORD=storiespass
            - PGDATABASE=stories
            - PGPORT=5432
        volumes:
            - type: bind
              source: ./api
              target: /code
        working_dir: /code
        command: bash -c "npm install && npm start"
        depends_on:
            - db

    client:
        image: node:12.18.4
        ports:
            - 8080:8080
        volumes:
            - type: bind
              source: ./client
              target: /client
        working_dir: /client
        command: bash -c "npm install && npm run dev"

    db:
        image: postgres
        volumes:
            - 'dbdata:/var/lib/postgresql/data'
            - './api/dbConfig:/docker-entrypoint-initdb.d/:al'
        environment:
            - POSTGRES_DB=stories
            - POSTGRES_USER=alicekres
            - POSTGRES_PASSWORD=storiespass
